safe:        false
auto:        false
server:      false

source:      ./public
destination: ./_site

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   true
